### ISSUE TITLE
二甲個人期末驗收

### ISSUE THREAD

**Issue by scrum-1** [scrum-1/scrum_cadp_final#1]
請每位學員利用電腦輔助設計實習課程中的機電資等相關技術, 以 [Solvespace](http://solvespace.com), [Onshape](https://www.onshape.com/), [Tinkercad](https://www.tinkercad.com/), [Arduino](https://www.arduino.cc/), [V-rep](http://www.coppeliarobotics.com/) 等工具, 建立可以在 [V-rep](http://www.coppeliarobotics.com/) 環境中運作的[彈珠檯](https://raw.githubusercontent.com/scrum-1/scrum_cadp_final/gh-pages/mech_design/cad_designs/pinball.jpg)模擬 (彈珠檯發球系統與檯盤內容必須自行設計).

各學員請從啟動可攜程式系統開始, 建立 CAD 零組件, 轉入 V-rep, 加入機電資元件之過程, 配合文字說明, 以 ShareX 拍成影片後, 上傳到個人 Youtube 帳號後, 登入個人 Github 帳號, 依照下列格式, 在本 Issue 下方, 以 Comment 方式, 提供所完成的連結.

範例:

學號: 7654321
個人驗收影片: https://www.youtube.com/watch?v=2rYHRxvoOhQ
個人心得: 請提供操作心得

**Comment by s40523135** [comment]
學號: 40523135
個人驗收影片: https://youtu.be/ZR_bR-pMbC8
個人心得: 模擬的時候要把物體的干涉和動力打開，設置軸的時候要整理好零件之間的關係（類似樹枝網路）但是我還是不會如何將底下的軸設置為彈簧，讓他可以把落下來的小球彈上去。

**Comment by s40523132** [comment]
學號: 40523132
個人驗收影片: https://www.youtube.com/watch?v=dVZkaXO2_3Q
個人心得:在模擬的過程中，我的球在落下的時候都會卡住，不會正常的往下掉，我也不知道要去哪裡修改這個問題，要過一段時間球才會慢慢的掉下去，發射球的那個彈簧我也不知道要去哪裡設定他，所以只能模擬到球往下掉到最下面。

**Comment by s40523139** [comment]
學號:40523139
個人驗收影片:https://www.youtube.com/watch?v=pkqfwg-iIDA&t=24s
個人心得:在模擬的時候，如果我把球桿的碰撞選項勾起來，會導致球桿運動不順加上連球都會卡住，但是如果我球桿只勾運動的選項，這樣球桿可以很順利的往前進，而且球也可以正常地掉落而不會卡住，但是我不知道要怎麼模擬出像彈簧一樣可以讓球射出去的方法。

**Comment by s40523122** [comment]
學號:40523122
個人驗收影片: https://youtu.be/J3Y4XDbP508
個人心得:關於彈簧模擬貌似可以用 joint/prismatic 功能做出，但最後研究許久還是無法做出理想狀態，所以以自由落體取代。參考 http://www.forum.coppeliarobotics.com/viewtopic.php?f=9&t=388 的留言作法。

**Comment by s40523101** [comment]
學號: 40523101
個人驗收影片: https://youtu.be/iccf63uawj8
                       https://youtu.be/M6ypXlnyyMU
個人心得:在Vrep上不能做彈簧得模擬 因為彈簧不是剛體
  
  @scrum-1  上次上課的時候有請問您運球機構是否能使用彈簧您告知我彈簧不是剛體無法做模擬

**Comment by scrum-1** [comment]
@s40523101 結論不要下得這樣快, V-rep 能否納入彈簧模擬, 或者彈簧是不是剛體, 都必須再找些資料佐證或進一步說明之後再下結論.

**Comment by s40523145** [comment]
學號:40523145
個人驗收影片:https://www.youtube.com/watch?v=DDwLmsGTO_U&t=1603s
彈珠軌道系統成果: https://www.youtube.com/watch?v=PKRDGNYo1MM&t=1s
個人心得:這學期要設計一個剛球軌道系統，尺寸必須在郵局box 2 中23/18/19cm，我的推球機構使用凸輪來進行提球，在onshape繪製好零件就可匯出成stl檔，再放入v-rep進行動態模擬，得出結果在機構的改良。

**Comment by s40523104** [comment]
學號:40523104
個人驗收影片(彈珠台):https://www.youtube.com/watch?v=ui1S0V9AX2E&feature=youtu.be
個人心得:彈珠台畫起來很快，但是因為v-rep不熟練因此拍影片前詢問了很多。等待會寫推球的程式後就可以當彈簧了。

**Comment by s40523120** [comment]
學號: 40523120
個人驗收影片: https://youtu.be/FybGOdw5joY
個人心得:  初次使用，下次繳更好的 。 需深究vrep

**Comment by s40523143** [comment]
學號: 40523143
個人驗收影片: https://www.youtube.com/watch?v=ZMSadI3w088&feature=youtu.be
個人心得: 我覺得第一次使用還不算很熟悉 ,需要時間去了解 ,去學習 。

**Comment by s40523111** [comment]
學號 : 40523111
個人驗收影片 :https://youtu.be/k17eIU7Eo8A
個人心得 :由於不善於使用vrep，所以很多功能沒用到。例如 : 用彈簧來敲擊彈珠，使彈珠運動。需花費更多鑽研vrep !

**Comment by s40523116** [comment]
學號 : 40523116
個人驗收影片 :https://youtu.be/9gpUDLvhXkY
個人心得 :因為第一次用vrep，所以很多功能不太會用。之後會再跟老師同學好好請教。

**Comment by s40523118** [comment]
學號 : 405231118
個人驗收影片 :https://youtu.be/r-KKEl7JjQI
個人心得 :因為聽說老師那邊才有推桿的程式串，所以這次沒有使用推桿，使用土法煉鋼的把球拉過來拉過去的方式

**Comment by s40423160** [comment]
學號 : 40423160
個人驗收影片 :https://www.youtube.com/watch?v=Gc2bmP6meno&t=6s
個人心得 :因為沒有使用彈簧，所以球只能自由落下，VREP還是有很多功能自己都還不會使用，之後如果需要模擬彈簧的部分，就要學會如何撰寫程式。

**Comment by s40523136** [comment]
學號: 40523136
個人驗收影片:https://www.youtube.com/watch?v=sa_cF6U9P4U
個人心得:
目前在onshape上繪製零件已經很熟悉了，但在V-rep上進行鋼球模擬很多功能還不是很熟悉，雖然老師有示範用程式的方式來達到鋼球發射，但我用其他辦法自行摸索多次，並且經過多次測試還是無法達到預期效果，所以我利用目前所學會的功能拍攝了只能讓球從高處進行自由落體的模擬。

**Comment by s40523130** [comment]
學號: 40523130
個人驗收影片: https://www.youtube.com/watch?v=CLcTnrgXC9k
個人心得: 在onshape上繪製零件已經很熟悉了，不過oneshape有些功能不能做到像Inventor的功能，但是在一起協同的功能非常棒在左上角可以看的到有誰編輯了零件，也可以返回之前的版本，這次在V-rep還有很多功能不是很熟悉

**Comment by s40523129** [comment]
學號:40523129
個人驗收影片:https://www.youtube.com/watch?v=7a-uuEI2Szg&t=7s
個人心得:用onshape繪圖會有些不習慣，但是能夠在線上繪圖很方便，V-rep有很多很多的功能但是我還不太會操作

**Comment by s40523146** [comment]
學號:40523146
個人驗收影片:https://www.youtube.com/watch?v=eUMEQWWyyGc&feature=youtu.be
個人心得:vrep是一個可以讓設計更接近實體化的東西，當設計出來的產品沒辦法在vrep上面模擬或是很不穩定時，因為加工的因素實際狀況通常會更糟，所以V-rep在機械設計就扮演著很重要的角色，只是因為是英文的學起來更加吃力，所以還要再多加油

**Comment by s40523134** [comment]
學號: 40523134
個人驗收影片:https://www.youtube.com/watch?v=ydMUWeXxYqY&feature=youtu.be
個人心得: 請提供操作心得運用onshape畫出彈珠台這部分沒什麼問題，但是再放入v-rep模擬的部分就還不太熟悉，不過感覺v-rep是非常好用的東西，會再多練習更熟練的使用它的

**Comment by s40523123** [comment]
學號: 40523123
個人驗收影片:https://www.youtube.com/watch?v=TzbE_5nZb_s
個人心得: Solvespace, Onshape, V-rep等等程式的運用能力經過學習後漸漸的在加強。老師利用方塊施力取代彈簧的方法目前還需要再研究，影片只使球從高處落在彈珠檯上運動做模擬。程式使用上的問題雖然無數，但正在一一的被解決，相信往後能有更熟練的操作。

**Comment by s40523201** [comment]
學號:40523105
個人驗收影片:https://www.youtube.com/watch?v=H-fDQoRlB8A&feature=youtu.be
個人心得:用onshape繪圖，並且使用V-rep軟體模擬，操作使用上很不熟悉，需要多加練習才會更熟練。

**Comment by s40523105** [comment]
學號: 40523105
個人驗收影片:https://www.youtube.com/watch?v=H-fDQoRlB8A&feature=youtu.be
個人心得: 使用Onshape繪圖，並開啟 V-rep模擬程式進行模擬，一開始不太會使用這兩個軟體，不過多操作幾次就熟悉多了，之後進行模擬就會順暢許多。

**Comment by s40523107** [comment]
學號:40523107
個人驗收影片:https://www.youtube.com/watch?v=NpHAH0TJx28 https://www.youtube.com/watch?v=YDhHJTVUf2c
個人心得:這學期在onshape上得使用已經慢慢熟習了,但在V-rep上得使用還有很多的不懂的地方,之後深入研究V-rep因該在操作上能更順利。

**Comment by 40423246** [comment]
學號:40423246
個人驗收影片:https://www.youtube.com/watch?v=9EoFMy_wFGo&feature=youtu.be
個人心得: 由於onshape跟solidwork相似，畫圖上並沒有什麼困難之處，但由於v-rep是一套完全自己要設定模擬軟體，在設定方面還需要再熟悉才能順利將想要的狀況給模擬出來。

**Comment by s40523128** [comment]
學號:40523128
個人驗收影片:https://www.youtube.com/watch?v=2IKqmYp_Few&t=6s
個人心得: 一開始用onshape不熟悉 ,有些功能找不到 ,但久了就習慣了 ,再來是v-rep ,真的要花時間去熟悉它 ,彈珠檯模擬也是試了幾次才成功。

**Comment by s40523125** [comment]
學號：40523125
個人驗收影片：https://www.youtube.com/watch?v=hxHmF3I3lT4&feature=youtu.be
個人心得：Onshape的功能使用上跟Solidwork真的很像，所以平常使用Solidwork習慣的我用起來很容易上手，雖然功能上還是簡便的點，但只需要開啟網頁就能繪圖真的是很方便，而在V-rep上就遇到許多困難，全英文的介面對我來說需要一些時間來查詢單字和摸索，詢問了幾位有經驗的同學後也慢慢了解一些功能的應用，在最後終於順利完成模擬情形了。

**Comment by s40523133** [comment]
學號:40523133
個人驗收影片:https://youtu.be/sRtJYnzRYjY
個人心得:這次的零件圖在onshape上畫出，雖然功能不像平常使用的繪圖軟體多樣，但習慣之後也是蠻好使用的，這次驗收比較難的地方在於在v_rep上模擬，全英文的介面使得我不知該如何下手，修改零件碰撞的地方找了不久的時間，連零件擺放的方法也是，一開始用了修改位移的方法，慢得看不下去，之後才找到比較快的直接抓位置的地方，最後才完成了這次的模擬，用onshape作圖大概已經沒有問題了，但v_rep還要多看看它的功能。

**Comment by s40523144** [comment]
學號:40523144
個人驗收影片:https://www.youtube.com/watch?v=m8xpfxiJ9ng
個人心得:在oneshape上畫畫還蠻好用的可以畫出多樣性的東西，但畫出來要放在v-rep就比較難了，現在還有點搞不懂怎麼模擬一些東西，也問了會的同學，像基本的碰撞及數度一些等等的參數，這是之前都從未接觸的東西，對這東西還蠻有興趣的，但還是要多多磨練，畢竟一堆英文跟未知的專有名詞都不懂，會繼續加油的。

**Comment by s40523121** [comment]
學號:40523121
個人驗收影片: https://www.youtube.com/watch?v=fjHSg5KC4IU&t=33s
個人心得:這次雖然對於推球的方塊機構還是不太熟，但對於這個程式也稍微有熟悉度了，我覺得最麻煩的部分在於移動零件的時候，沒辦法很順暢的移動，要一步一步慢慢對它的位置，但可能是我還不夠熟悉，所以不曉得他的用法，那這次彈珠台算是蠻成功的都能夠成功掉在凹槽裡面。

**Comment by s40523126** [comment]
學號:40523126
個人驗收影片:https://www.youtube.com/watch?v=otR88iWr9Wg&feature=youtu.be
個人心得:雖上網查詢許多有關V-rep的用法,幾乎都是英文,對於推彈珠的機構還是不解,會繼續尋找更多資料,現在只能做到自由落體經過彈珠台的軌道,並不能讓他做往復的運動.

**Comment by s40523137** [comment]
學號:40523137
個人驗收影片:https://youtu.be/NtMYItwHCgA
個人心得:在onshape上繪製彈珠台後,為了替代彈簧改用滑塊來撞擊球,因此而外畫了一個滑塊,而在vrep模擬時要調整好滑撞撞擊球的方向,與其速度的調整,否則撞擊力道不夠,球會不能被驅動。

**Comment by 40523138** [comment]
學號: 40523138
個人驗收影片:https://youtu.be/hSPNYWNmCM8
個人心得: 在onshape上繪圖成熟許多，V-rep的模擬還需要加油 更加勤奮的練習

**Comment by s40523131** [comment]
學號:40523131
個人驗收影片:https://youtu.be/buKWLFyrQzk
個人心得:在 onshape上看到 solidework的影子，所以用起來不會太困難，一下子就熟悉了，反倒是v_rep花了不少時間去熟悉操作。

**Comment by s40523117** [comment]
學號:40523117
個人驗收影片: https://www.youtube.com/watch?v=aOQRIXT0BkQ&t=4s
                        https://www.youtube.com/watch?v=eP856a1Tz78
個人心得:    可能習慣使用其他繪圖軟體的操作模式，Onshape使用上較不順手，重複練習後較熟練些
                    使用V-rep模擬時，圓球的部分一直無法彈射，詢問同學後得以發射，但無法重複運作，仍在找尋方式

**Comment by s40523147** [comment]
學號：40523147
個人驗收影片： https://www.youtube.com/watch?v=HReF3zkbs1o
個人心得：當然還是先看同學們的影片後，在自己去嘗試看看。不試不會有結果，試過會很不一樣。有時候覺得自己摸會一些東西還滿屌的。雖然只是皮毛，但已足夠我學習的欲望!!!!

**Comment by 40423219** [comment]
學號:40423219
個人驗收影片:https://www.youtube.com/watch?v=v6-yhuqq3LI
個人心得:Vrep將鋼球放在彈珠台掉落較容易，如何將鋼球彈起並模擬才是需要思索的地方。

**Comment by s40523141** [comment]
學號：40523147
個人驗收影片：https://www.youtube.com/watch?v=qK6d-PfC0b8
個人心得: V-rep的使用還不熟悉以至於模擬中遇到很多瓶頸,用多了就可以駕輕就熟。

**Comment by s40523127** [comment]
學號：40523127
個人驗收影片：https://www.youtube.com/watch?v=V-DhcctI6iQ&feature=youtu.be
個人心得：這是我在Solidwork上繪製，在V-rep上進行模擬，而在V-rep就遇到許多操作上的困難，請教同學後才稍微學會操作，並且加入老師的程式，然後順利完成模擬。V-rep真的是很酷的程式，它可以為物體加上碰撞關係以及重力關係，讓模擬變得更加容易。

**Comment by s40523119** [comment]
學號: 40523119
個人驗收影片: [影片連結](https://youtu.be/rv257iJrf0k)
個人心得: 

本次的課程，對我來說有許多任務得去挑戰，這次彈珠檯的題目，每一個環節都會影響到後續模擬與測試。在設計零組件時的公差配合，組合建所選接合條件，甚至是繪製的步驟，都會影響後續在 *V-REP* 內的模擬。不管是在雲端的Onshape或是近端的SolidWords、Inventor...等等的CAD軟體，操作上大多大同小義，並不會是本次題目中會遇到的障礙。

本次所選用的模擬軟體 *V-REP* ，可以說是機器人模擬軟體中的霸主，除了開源之外，也提供了免費的教育版本，看起來似乎與專業版沒有什麼差異。在彈珠檯的模擬當中，為了講求真實，內建了四種不同的物理引擎(ODE, Bullet, Vortex, Newton)，除了數學之外還是數學，所以對於匯入的物件本身就有一定要求，本次課程採用 *STL* 檔案類型，STL檔案僅描述三維物體的表面幾何形狀，是小面積湊出來的近似面(三角形)，更多資訊可參照 [STL](https://zh.wikipedia.org/wiki/STL_(%E6%AA%94%E6%A1%88%E6%A0%BC%E5%BC%8F))
。所以匯入進V-REP內，零件所呈現的是各個菱角的點，對於物體實際模擬情形，物理運算上會出現疑慮，碰撞模擬運用大量的布林值運算，可能很多人的球體會在彈珠檯上卡在某個位置動來動去，這可能就是物理運算的質點進入一個凹陷的角落，造成程式判斷不斷與旁邊的點做碰撞，讓你的球卡在那，或是在滾動時，有許震動，使用V-REP的最終目的，是希望程式模擬的結果能夠符合現實生活中的情形，所以勢必省去一些會造成運算上的困難的累贅，就必須簡化模型，讓運算時減少負擔。

功能齊全且強大的軟體，相較之下，學習取現相對的陡峭很多，這個軟體的設定時在琳瑯滿目，不看手冊是不可能的。想要快速學習 V-REP的辦法就是將官方的教學文檔與範例，手把手的實際演練一次，除了軟體技能提升之外，也能夠清楚在模擬時需要注意那些特性。

**Comment by S40523102** [comment]
學號:40523102
個人驗收影片:https://youtu.be/WqynpHAEEIw

個人心得: 第一次自己從設計到模擬，途中困難重重，從尺寸的設計，外觀的編輯，以及V-rep模擬的使用，也問了同學以及參考同學的影片，慢慢摸索才用出成品，雖然還有點卡卡的，但會繼續努力

**Comment by s40523106** [comment]
學號:40523106
個人驗收影片:https://youtu.be/16M2CAxyZYo

個人心得: 使用onshape繪製後，在V-rep模擬，從剛開始覺得很困難到最後多嘗試就熟悉很都，但最後要模擬的時候彈珠滾動時沒有成功。

**Comment by s40523115** [comment]
學號:40523115
個人驗收影片:https://www.youtube.com/watch?v=DoKVtuGmWGg

個人心得:最初做這個感覺十分困難，但在同學的教導，以及我的努力下還是把東西做出來了，在這個影片下我也學習到很多東西感覺受益良多。
