### ISSUE TITLE
二乙個人期末驗收

### ISSUE THREAD

**Issue by scrum-1** [scrum-1/scrum_cadp_final#2]
請每位學員利用電腦輔助設計實習課程中的機電資等相關技術, 以 [Solvespace](http://solvespace.com), [Onshape](https://www.onshape.com/), [Tinkercad](https://www.tinkercad.com/), [Arduino](https://www.arduino.cc/), [V-rep](http://www.coppeliarobotics.com/) 等工具, 建立可以在 [V-rep](http://www.coppeliarobotics.com/) 環境中運作的[彈珠檯](https://raw.githubusercontent.com/scrum-1/scrum_cadp_final/gh-pages/mech_design/cad_designs/pinball.jpg)模擬 (彈珠檯發球系統與檯盤內容必須自行設計).

各學員請從啟動可攜程式系統開始, 建立 CAD 零組件, 轉入 V-rep, 加入機電資元件之過程, 配合文字說明, 以 ShareX 拍成影片後, 上傳到個人 Youtube 帳號後, 登入個人 Github 帳號, 依照下列格式, 在本 Issue 下方, 以 Comment 方式, 提供所完成的連結.

範例:

學號: 7654321
個人驗收影片: https://www.youtube.com/watch?v=2rYHRxvoOhQ
個人心得: 請提供操作心得

**Comment by 40423204** [comment]
學號: 40423204
個人驗收影片: https://youtu.be/pe3F861CQxI
個人心得: 就只是单纯的放个球上去让他运动，那个弹簧我不会

**Comment by 40371215** [comment]
學號: 40371215
個人驗收影片:https://www.youtube.com/watch?v=fh1osWCdNAQ
個人心得: 彈珠台的繪製很容易 可是在V-rep上面卻很難定位 且線性運動的設定我還不會 只會插入選轉軸而已 或是用馬達插入連趕機構來進行 可是太麻煩

**Comment by s40523230** [comment]
學號: 40523230
個人驗收影片: https://youtu.be/bU_GblXFkGc
個人心得: 這個製作彈珠台的作業，讓我更加了解v-rep的操作方式，以及基本操作

**Comment by s40523243** [comment]
學號：40523243
個人驗收影片(彈珠台)：https://www.youtube.com/watch?v=EvmafKMwBG0
個人心得：把球放上去其實很簡單還有繪製彈珠台及鋼球,基本操作就只有這樣
個人驗收影片(鋼球軌道模擬):https://www.youtube.com/watch?v=A3ACxl0PbP8&feature=youtu.be

**Comment by s40523234** [comment]
學號：40523234
個人驗收影片：https://youtu.be/O33QuyenlmI
個人心得：繪製的過程比較簡單，但是定位很麻煩，有些功能還不了解

**Comment by s40523226** [comment]
學號：40523226
個人驗收影片:https://youtu.be/eUKikpDBrHU
個人心得：繪製的過程比較簡單，但是定位很麻煩，調整觸碰和動態了解不深。

**Comment by s40523207** [comment]
學號:40523207
個人驗收影片:https://www.youtube.com/watch?v=ncEBehzBMTw&feature=youtu.be
個人心得:Vrep我還需要加強孰練，彈珠及彈珠台設計簡單自由，利用Vrep模擬可以快速找出機構運動時的錯誤

**Comment by 40371235** [comment]
學號:40371235
個人驗收影片:https://www.youtube.com/watch?v=msRgsNHmopw
個人心得:對於Onshape繪製過程以比較熟練，但V-rep的操作與模擬比較不熟悉 只會利用重力讓球掉下來而已

**Comment by 40523249** [comment]
學號: 40523249
個人驗收影片: https://www.youtube.com/watch?v=bptP3zjTfVY&feature=youtu.be
個人心得: 對於Vrep並不熟悉,因此私下練習的時候往往一直出錯,但是在錯誤中學習也是必要的,希望未來在使用Vrep能夠更順暢熟練

**Comment by 40023139** [comment]
學號: 40023139
個人驗收影片:https://youtu.be/FCkx2h-UUHQ
個人心得: 
onshape繪製已經很熟悉，V-rep部分還有些細節需要再研究，這次只讓球自由落下，並沒有加上彈射機構，模擬的時候有特別多加幾顆球上去，看看從不同的地方滾落的狀況，以及檢討整體設計，統整出以下。彈珠檯設計心得統整一下設計重點
1.球檯上障礙物布置(包含外框)，其上下左右間距需大於鋼球直徑，才不會使球卡住
2.底面須放置一斜面，讓球回歸到彈射位置
3.個人想法，無實作，彈射機構不一定要使用彈簧，在v-rep內，匯入一塊板子，用joint>>revolute控制讓一個角度往復運動，模擬夜市用手打彈珠的動作
4.鋼球彈射出去的方向，我的設計在球檯右上角的地方，應該要使用圓弧，而非直角

**Comment by s40523246** [comment]
學號: 40523246
個人驗收影片:https://www.youtube.com/watch?v=-1V-387AWh0
個人心得:
1.剛使用onshape繪圖軟提繪製時，並不是很熟悉其操作，但是花了幾個禮拜的摸索之後，也慢慢步入軌道，試著設計彈珠台。
2.設計彈珠台的理念:(1)以傾斜方式，以利彈珠滾下去
                                 (2)在軌道上方，需倒圓角，不燃彈珠會卡在原地返回
                                 (3)彈珠台內的障礙物設計，其間距需大於鋼球直徑
3.使用V-rep模擬系統，第一次使用那麼厲害的軟體，覺得相當困難，加上裡面很多都是英文，但藉由自學能力，以記我在大學學到的東西加以研究，也順利的讓它運轉了。

**Comment by s40523211** [comment]
學號: 40523211
個人驗收影片:https://youtu.be/o9msH7Sgi-0
個人心得: 利用onshape繪製已經相當熟練上手,但vrep在經過摸索和練習下只會簡單的操作

**Comment by s40523226** [comment]
學號：40523226
個人驗收影片:https://youtu.be/eUKikpDBrHU
個人心得：繪製的過程簡單，但是定位z軸很麻煩，調整觸碰和動態了解不深。

**Comment by s40523244** [comment]
學號: 40523244
個人驗收影片:https://www.youtube.com/watch?v=faHFn0T_38g&feature=youtu.be
個人心得:剛開始使用VREP時，有點不熟悉，在研究過後終於成功模擬，不過還是不知道怎麼設定拉桿，是比較可惜的地方

**Comment by s40523232** [comment]
學號:40523232
個人驗收影片:https://www.youtube.com/watch?v=rL9rKQUkzIs
個人心得:從最初的設計都是需要自己構想,不須太拘束,尺寸都要自己定義,第一次使用模擬程式還不太熟悉,所以有些步驟不太順手,彈簧這部分較複雜,用了很久最後還是沒有成功.作品並不完美.但這次使用vrep非常有趣.

**Comment by s40523212** [comment]
學號:40523212
個人驗收影片:[https://youtu.be/QAkfOhfNrgs](https://youtu.be/QAkfOhfNrgs)
個人心得:很有趣，從自己設計到成功模擬，非常有成就感，但是對於程式還是有些不熟悉，需要在熟練才行。

**Comment by s40523209** [comment]
學號:40523209
個人驗收影片:https://youtu.be/9S5NZ9e
個人心得:繪製出彈珠臺用vrep模擬操作不太熟悉。

**Comment by s40523209** [comment]
學號:40523209
個人驗收影片:https://www.youtube.com/watch?v=9S5NZ9eLuK8&feature=youtu.be
個人心得:繪製出彈珠臺用vrep模擬操作不太熟悉。

**Comment by s40523218** [comment]
學號:40523218
個人驗收影片:https://youtu.be/xXqEjYLaxc4
個人心得:彈珠檯繪製的比較簡單,V-rep的定位和讓軸轉動還不太熟悉

**Comment by s40523214** [comment]
學號:40523214
個人驗收影片:https://youtu.be/nNiT8PuvGTA
個人心得:匯入零件時，單位使用 cm 相對來講看起來比較簡潔，再運用簡單的碰撞和動力計算模擬。由於不熟悉介面，希望可以更加流暢的操作V-rep。

**Comment by s40523220** [comment]
學號:40523220
個人驗收影片:https://www.youtube.com/watch?v=wZq6mR0t4YM
個人心得:學會簡單使用vrep，但彈簧還不會使用。

**Comment by 404232077** [comment]
學號:40423207
個人驗收影片https://www.youtube.com/watch?v=lxP7ASdNDXk&feature=youtu.be
個人心得:獨一無二朱修林彈珠檯。

**Comment by 40423241** [comment]
學號: 40423241
個人驗收影片: https://youtu.be/DYKsRXOnko0
個人心得: 利用solidworks繪製彈珠檯再轉入vrep，彈珠台繪製起來沒有困難，難的是轉入vrep之後的設定。

**Comment by s40523210** [comment]
學號: 40523210
個人驗收影片: https://youtu.be/fLBEB88ebY8
個人心得: 使用solidworks來繪製彈珠檯 繪製過程沒有很難 再來轉STL檔 再轉入V-rep進行模擬 想要模擬彈簧的碰撞.. 但是內容為英文 看不太懂 所以沒有進行彈簧模擬 而是比較簡單的 放入鋼球 沿著彈珠台滾動

**Comment by 40423224** [comment]
學號: 40423224
個人驗收影片:https://youtu.be/mX0nFnAJ-pI
個人心得:繪圖軟體是solidworks，再轉成STL檔案，在V-rep中打開，然後進行模擬，只是彈簧的運動因為能力不夠簡略。

**Comment by s40523205** [comment]
學號: 40423205
個人驗收影片:https://www.youtube.com/watch?v=_Mum89_SXpc
個人心得:因為onshape 用起來比較不習慣，所以選擇用solidworks，再轉成STL檔，至vrep模擬，從畫圖到模擬幾乎都是自己操作，成就感upup。

**Comment by s40523206** [comment]
學號: 40523206
個人驗收影片: https://www.youtube.com/watch?v=y3YenI4TPKA&feature=youtu.be
個人心得: 先用Onshape畫彈珠台，轉檔後再V-rep，有點不熟悉V-rep的操作，剛開始會感到困難

**Comment by s40523236** [comment]
學號: 40523236
個人驗收影片:https://youtu.be/1MeDHlNCZBs
個人心得:使用的繪圖軟體是soildworks 轉成STL檔 在繪製彈珠台的零件較為簡單，但V-rep較不熟悉，剛開始在操作使用時較困難。

**Comment by s40523224** [comment]
學號: 40523224
個人驗收影片:https://youtu.be/8F8lhjY_jWg
個人心得:在使用vrep模擬十，因為都不懂參數設定所以進行模擬的時候會很不真實．

**Comment by s40523227** [comment]
學號:40523227
個人驗收影片:https://youtu.be/Dn1E53wmrFY
個人心得:畫彈珠台很簡單，但是還不太熟練操作V-rep模擬，到了下學期開始上協同設計的時候，應該就比較熟練了。

**Comment by 40423159** [comment]
學號: 40423159
個人驗收影片: https://www.youtube.com/watch?v=es5rqqJSqkQ&t=
個人心得: 我是在SolidWorks上繪製彈珠台的，載入Onshape時就不能改圖了，圖設計有一些小問題，以至於在v-rep作動時，球沒有回到最底下，希望之後能把v-rep學好．還不是很懂v-rep這個軟體，

**Comment by s40523240** [comment]
學號:40523240
個人驗收影片:https://www.youtube.com/watch?v=3t6GrQ1lnaY
個人心得:彈珠台是利用SolidWorks繪製再儲存成STL檔，接著在vrep裡開啟，操作vrep模擬不是件容易的事，需要多練習幾次步驟才會熟悉。

**Comment by s40523248** [comment]
學號:40523248
個人驗收影片:https://www.youtube.com/watch?v=dSQu47Tw93A
個人心得:我是利用onshape繪製彈珠台，onshape是第一次使用，所以用它繪製，再轉成STL檔，至vrep模擬，vrep不熟，所以花費了不少時間，但學會後想必是一個很好的工具，希望往後能熟練它。

**Comment by s40523231** [comment]
學號:40523231
個人驗收影片https://youtu.be/YWWyQbmQo1A
個人心得:使用的軟體是soildworks  之後再轉成STL檔 雖然V-rep不會使用 之後多練習幾次就比較熟悉了。

**Comment by s40523204** [comment]
學號:40523204
個人驗收影片https://www.youtube.com/watch?v=AsLHPZwaQ48
個人心得:利用SolidWorks繪製了彈珠台，以及用vrep模擬，模擬成功後很有成就感，原來自己也能完成獨一無二的彈珠台。

**Comment by s40523233** [comment]
學號:40523233
個人驗收影片https://www.youtube.com/watch?v=jSWLyg2XP7M
個人心得:利用SolidWorks繪製彈珠檯，轉成檔案放入程式vrep，再去設定球的大小和位置，再用Share X錄製影片。自己設計自己理想形狀的彈珠台，讓彈珠可以順利地從彈珠台滑下。

**Comment by s40523203** [comment]
學號:40523203
個人驗收影片https://www.youtube.com/watch?v=h7TmzT09AEs
個人心得:利用onshape繪製彈珠台，再匯入vrep，但是不會用彈簧，所以只能模擬求落下和滾動路徑。

**Comment by s40523201** [comment]
學號:40523201
個人驗收影片:https://www.youtube.com/watch?v=rTgeidNlgko&feature=youtu.be
個人心得:使用Onshape繪製彈珠台，第一次使用V-rep模擬，再加入球，調整球的位置有點困難，不過最後有成功。

**Comment by s40523245** [comment]
學號: 40523245
個人驗收影片: https://www.youtube.com/watch?v=rECfRF6vafA&feature=youtu.be
個人心得: 利用onshape畫彈珠台以及利用V-rep模擬彈珠滾動，因為不太會用V-rep所以調整位置的時候用了很久。

**Comment by s40523242** [comment]
學號: 40523242
個人驗收影片:https://www.youtube.com/watch?v=8643UNYebXk&feature=youtu.be
個人心得: 用onshape畫彈珠台，把球和彈珠台存成STL檔，匯入V-rep模擬，不太熟練V-rep調整球的位置用了有點久。

**Comment by s40523239** [comment]
學號: 40523239
個人驗收影片:https://www.youtube.com/watch?v=-I4M8IoWl1o
個人心得:使用Onshape在線上設計並畫出彈珠台，第一次使用這軟體發現還是solidworks好用，但onshape的好處就是他能夠和他人線上共享一起編輯再回推回去，很方便，畫完後下載.stl檔利用Vrep模擬軟體試跑彈珠台，雖然都是英文看不太懂但問過其他同學後了解怎麼操作，並把過程錄製成影片

**Comment by s40523216** [comment]
學號: 40523216
個人驗收影片:https://www.youtube.com/watch?v=s2FeVR0y5dA&feature=youtu.be
個人心得:彈珠台的繪製都還算簡單,但是要模擬彈珠台的運作卻蠻難的,尤其是要定位

**Comment by 40423250** [comment]
學號: 40423250
個人驗收影片:https://youtu.be/7rYUoEyM6Co
個人心得: 彈珠台的繪製很容易 可是在V-rep上面卻很難定位 且線性運動的設定較為困難 只會插入鋼球以及軸而已 不過可以知道這件軟體能模擬相當的案件 須好好研究

**Comment by s40523237** [comment]
學號：40523237
個人驗收影片:https://www.youtube.com/watch?v=k7KomMyZDaI&feature=youtu.be
個人心得：彈珠台方面的設計繪圖並不會是太難。然而在進行模擬時卻常遇到空隙未設定好而發生錯誤，而且在一開始進行vrep設定時也因為看不懂而詢問諸多同學。最後最不明瞭的就是發射的彈簧要如何設定。

**Comment by s40523229** [comment]
學號：40523229
個人驗收影片:<a href="https://www.youtube.com/watch?v=7CxXdQu9nNE&feature=youtu.be">youtnbe</a>
個人心得：使用onshape繪製彈珠台,內部的斜度跟發力的彈簧十分需要設計,但在vrep模擬時球的定位跟重量需要慢慢去調整,不過讓我更熟悉了vrep的操作

**Comment by 40423231** [comment]
學號：40423231
個人驗收影片:https://youtu.be/c551obZxzWE
個人心得：使用onshape繪製彈珠台跟ball, 然而在進行模擬時卻常遇到空隙未設定好而發生錯誤,模擬彈珠台的運作卻蠻難的

**Comment by 40523250** [comment]
學號：40423235
個人驗收影片:https://www.youtube.com/watch?v=gbU8daHyDbc
網誌介紹:https://cadpb.kmol.info/40523250/doc/trunk/blog/2017-fall-cadp-w16.html
個人心得：在完成鋼球運動系統後，利用相同的原理製作出彈珠台，無論在熟練度及設計速度接突飛猛進。

**Comment by s40523219** [comment]
學號: 40523219
個人驗收影片: https://youtu.be/bymstGd8MNY
個人心得: 繪製彈珠檯個零件方面相當簡單，大約五分鐘即可完成零件繪製，也參考老師影片教學，利用彈力方塊給予其限制，完成了使用v-rep進行彈珠的測試。

**Comment by 40423220** [comment]
學號:40423220
個人驗收影片:https://www.youtube.com/watch?v=2cso0Jri-zE
個人心得:彈珠檯比鋼球模擬系統簡單多了，但是彈力的部分還有待加強，onshape繪製零件v-rep模擬這兩套軟體配合很好用。

**Comment by s40523215** [comment]
學號:40523215
個人驗收影片:https://www.youtube.com/watch?v=nt7MWGIZTVM
個人心得:我覺得畫彈珠台不是很困難,但是在v-rep模擬系統真的是有很大的困難,要設定很多東西還有一堆不認識的英文,但是模擬出來很有成就感。

**Comment by 40423213** [comment]
學號: 40423213
個人驗收影片:https://vimeo.com/251321149
個人心得: 把彈珠台繪圖後，放入V-rep裡進行模擬。

**Comment by 40423233** [comment]
學號: 40423233
個人驗收影片:https://vimeo.com/251328043
個人心得: 繪製彈珠台的過程有趣 模擬也很有趣

**Comment by s40523213** [comment]
學號：40523213
個人驗收影片：https://www.youtube.com/watch?v=7UGWi75Jzd0 
個人心得：彈珠台比鋼球模擬系統簡單多了，雖然不會用彈力的部分，但是模擬出來很有成就感。
